### ISSUE TITLE
[REG] The labels should start from 1, which is not that obvious

### ISSUE THREAD

**Issue by RaneemQaddoura** [gugarosa/opfython#5]
I would like to thank you for providing the source code

I have a comment, the labels should start from 1 in order for the code to work, which might not be obvious for some. I just like to bring this to your attention as many datasets have the label of 0.

**Comment by gugarosa** [comment]
Hello Raneem! I hope everything is going well with you.

LibOPF has been designed to work with labels starting from one, since its first implementation in C (https://github.com/jppbsi/LibOPF). Thus, as we re-implemented the whole package from C to Python, we opted to maintain such a behavior.

To improve the user experience, we added an exception whenever a label input is smaller than 1 (https://github.com/gugarosa/opfython/blob/master/opfython/core/node.py#L100, https://github.com/jppbsi/LibOPF/wiki/OPF-file-format-for-datasets), so the user can be aware that such behavior is expected when using OPFython.

You can easily increment the label of any dataset by using the following:
```
Y += 1
```
where `Y` stands for an array holding your labels.

Nevertheless, to make users more aware, we have just added a reference to such a behavior in our Wiki (https://github.com/gugarosa/opfython/wiki/OPF-File-Format) and in our examples (https://github.com/gugarosa/opfython/tree/dev/examples/applications), which will go live in our next deploy.

Thank you for your concern and best regards,
Gustavo.

**Comment by RaneemQaddoura** [comment]
Thank you for your fast reply.
Yes, the exception is clear and the labels can be easily adjusted.
